import { StyleSheet } from "react-native";
import { verticalScale, scale } from "../../responsiveScaling";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    marginBottom: verticalScale(7),
  },
  subContainer: {
    marginHorizontal: scale(12),
  },
  notesContainer: {
    justifyContent: "center",
    alignItems: "center",
    marginTop: verticalScale(40),
    marginBottom: verticalScale(8),
    width: "100%",
  },
  notes: {
    width: scale(102),
    height: verticalScale(33),
    fontFamily: "Gilroy-ExtraBold",
    color: "#000000",
    fontSize: scale(27),
    textAlign: "center",
    lineHeight: verticalScale(33),
    marginBottom: verticalScale(8),
  },
  personal: {
    width: scale(215),
    height: verticalScale(21),
    fontFamily: "Gilroy-Medium",
    color: "#000000",
    fontSize: scale(18),
    textAlign: "center",
    lineHeight: verticalScale(21),
  },
  notesImage: {
    width: "100%",
    height: verticalScale(270),
  },
  notesImageStyle: {
    borderRadius: 16,
  },
  imageTextContainer: {
    position: "absolute",
    left: scale(12),
    bottom: verticalScale(1),
  },
  imageText: {
    color: "#FFFFFF",
    width: scale(125),
    height: verticalScale(22),
    fontFamily: "Gilroy-ExtraBold",
    fontSize: scale(22),
    lineHeight: verticalScale(22),
    marginBottom: verticalScale(5),
  },
  imageSubText: {
    color: "#FFFFFF",
    width: scale(192),
    height: verticalScale(40),
    fontFamily: "Gilroy-Medium",
    fontSize: scale(15),
    lineHeight: verticalScale(18),
  },
  interestedContainer: {
    flex: 1,
    flexDirection: "row",
    marginTop: verticalScale(14),
    marginBottom: verticalScale(14),
  },
  interestedSubContainer1: {
    flex: 0.7,
    flexDirection: "column",
    marginLeft: scale(12),
  },
  interestedSubContainer2: {
    flex: 0.3,
    alignItems: "flex-end",
    alignSelf: "flex-end",
  },
  upgradeButton: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#FCDF03",
    textAlign: "center",
    width: scale(113),
    height: verticalScale(50),
    borderRadius: scale(24.5),
  },
  upgradeText: {
    color: "#000",
    width: scale(62),
    height: verticalScale(23),
    fontFamily: "Gilroy-ExtraBold",
    fontSize: scale(15),
    lineHeight: verticalScale(23),
  },
  interested: {
    color: "#000",
    width: scale(173),
    height: verticalScale(25),
    fontFamily: "Gilroy-Bold",
    fontSize: scale(22),
    lineHeight: verticalScale(27),
    marginBottom: verticalScale(5),
  },
  premiumText: {
    color: "#9B9B9B",
    width: scale(192),
    height: verticalScale(33),
    fontFamily: "Gilroy-Medium",
    fontSize: scale(15),
    lineHeight: verticalScale(18),
  },
  likesContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  likesImage: {
    width: scale(164),
    height: verticalScale(255),
  },
  topic: {
    width: scale(150),
    height: verticalScale(33),
    fontFamily: "Gilroy-ExtraBoldItalic",
    color: "#000000",
    fontSize: scale(27),
    textAlign: "center",
    lineHeight: verticalScale(33),
    marginBottom: verticalScale(160),
  },
  genericMsg: {
    width: scale(215),
    height: verticalScale(45),
    fontFamily: "Gilroy-Medium",
    color: "#9B9B9B",
    fontSize: scale(18),
    textAlign: "center",
    lineHeight: verticalScale(21),
  },
});
